cookie:
  expiry_days: 30
  key: a_truly_unique_and_random_key # Замени на свою случайную строку
  name: ots_auth_cookie
credentials:
  usernames: {} # Пользователи будут добавляться сюда после регистрации.
  preauthorized:
    emails:
    - alex.zorg.1@mail.ru
    - imil_khayrullin@mail.ru
    - gonamsalinsky@gmail.com
